server:
  port: 17001

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:search-db
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

search:
  kakao:
    url: https://dapi.kakao.com/v2/search/web
    admin-key: ecfaa730aced1762c3d2cfe5aa37bcc3
  naver:
    url: https://openapi.naver.com/v1/search/blog.json
    client-id: uyODjAXWeVNmAg0hcYqf
    client-secret : U1ouaO8yJB